# Generated by Django 2.0.2 on 2019-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190319_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblog',
            name='blog_category',
            field=models.CharField(choices=[('P', 'Personal'), ('IT', 'IT'), ('D', 'DJango')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
