# Generated by Django 2.0.2 on 2019-03-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_newblog_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblog',
            name='firstpage',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
