# Generated by Django 2.0.2 on 2019-03-25 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_newblog_firstpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblog',
            name='blog_creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
