# Generated by Django 2.0.2 on 2019-04-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_newblog_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newblog',
            old_name='username',
            new_name='username_id',
        ),
    ]
