# Generated by Django 2.0.2 on 2019-04-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20190403_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblog',
            name='blogdate',
            field=models.DateField(null=True),
        ),
    ]
