# Generated by Django 2.0.2 on 2019-04-05 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20190403_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblog',
            name='blog_category',
            field=models.CharField(choices=[('P', 'Personal'), ('T', 'Travel'), ('F', 'Fashion')], max_length=1),
        ),
        migrations.AlterField(
            model_name='newblog',
            name='blogdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
