# Generated by Django 2.0.2 on 2019-04-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20190405_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblog',
            name='blogimage',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='pics/%y%m%d/'),
        ),
    ]
