# Generated by Django 2.0.2 on 2019-04-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_newblog_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblog',
            name='blog_category',
            field=models.CharField(choices=[('P', 'Personal'), ('T', 'Travel'), ('F', 'Fashion'), ('M', 'Music')], max_length=1),
        ),
    ]
