# Generated by Django 2.0.2 on 2019-04-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_auto_20190417_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.TextField()),
                ('rating', models.CharField(choices=[('Avg', 'Average'), ('Good', 'Good'), ('V Good', 'Very Good'), ('Excellent', 'Excellent')], max_length=9)),
                ('recommend', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
    ]
